name: ds-optimization
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch
  - pytorch-cuda=11.8
  - pip:
    - matplotlib>=3.0.2
    - opencv-python>=4.1.1
    - tqdm>=4.32.2
# run conda env create -f environment.yml
# update conda env update -f environment.yml --prune