name: tr-ocr
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.10
  - pip
  - pytorch=1.11
  - pytorch-cuda=11.8
  - torchvision=0.15.2
  - pip:
    - transformers
    - fastapi[all]
    - uvicorn[standard]
    - Pillow

# run conda env create -f environment.yml
# update conda env update -f environment.yml --prune